### ISSUE TITLE
Is there a way to set height of bottom bar

### ISSUE THREAD

**Issue by SB051** [Mindinventory/animated_notch_bottom_bar#17]
I want to set height. I tried to add Container above it but It has error
Error:
```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack
#2      AnimationController.stop
animation_controller.dart:772
#3      AnimationController.value=
animation_controller.dart:361
#4      AnimationController.reset
animation_controller.dart:382
#5      _AnimatedNotchBottomBarState.initState.<anonymous closure>
notch_bottom_bar.dart:106
#6      ChangeNotifier.notifyListeners
change_notifier.dart:403
#7      NotchBottomBarController.jumpTo
notch_bottom_bar_controller.dart:12
#8      _AnimatedNotchBottomBarState.build.<anonymous closure>.<anonymous closure>
notch_bottom_bar.dart:218
#9      BottomBarInActiveItem.build.<anonymous closure>
bottom_bar_inactive_item.dart:35
#10     GestureRecognizer.invokeCallback
recognizer.dart:275
#11     TapGestureRecognizer.handleTapUp
tap.dart:654
#12     BaseTapGestureRecognizer._checkUp
tap.dart:311
#13     BaseTapGestureRecognizer.handlePrimaryPointer
tap.dart:244
#14     PrimaryPointerGestureRecognizer.handleEvent
recognizer.dart:630
#15     PointerRouter._dispatch
pointer_router.dart:98
#16     PointerRouter._dispatchEventToRoutes.<anonymous closure>
pointer_router.dart:143
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#18     PointerRouter._dispatchEventToRoutes
pointer_router.dart:141
#19     PointerRouter.route
pointer_router.dart:127
#20     GestureBinding.handleEvent
binding.dart:488
#21     GestureBinding.dispatchEvent
binding.dart:468
#22     RendererBinding.dispatchEvent
binding.dart:333
#23     GestureBinding._handlePointerEventImmediately
binding.dart:413
#24     GestureBinding.handlePointerEvent
binding.dart:376
#25     GestureBinding._flushPointerEventQueue
binding.dart:323
#26     GestureBinding._handlePointerDataPacket
binding.dart:292
#27     _invoke1 (dart:ui/hooks.dart:186:13)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
(elided 2 frames from class _AssertionError)
The NotchBottomBarController sending notification was: Instance of 'NotchBottomBarController'
════════════════════════════════════════════════════════════════════════════════
```

**Comment by jignesh-mind** [comment]
Hi @SB051,
Add some minimal code and the platform type (app/web) to regenerate this exception.

**Comment by mi-raj04** [comment]
@SB051  we did not receive any response from your side so as of now we close this issue feel free to write us if need any help
